-- CLOUDS FoodPass: scanner event logs
-- Run this once in Supabase SQL Editor after the existing FoodPass SQL.

create table if not exists public.scanner_logs (
  id bigint generated by default as identity primary key,
  scanned_at timestamptz not null default now(),
  scanner_username text,
  student_id uuid,
  usn text,
  full_name text,
  year integer,
  result text not null,
  qr_token text
);

create index if not exists scanner_logs_scanned_at_idx
  on public.scanner_logs (scanned_at desc);

alter table public.scanner_logs enable row level security;

revoke all on table public.scanner_logs from public, anon, authenticated;

create or replace function public.scanner_log_scan(
  p_token text,
  p_qr_token text,
  p_result text
)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_username text;
  v_student public.students;
begin
  select a.username into v_username
  from public.staff_sessions s
  join public.staff_accounts a on a.id = s.staff_id
  where s.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    and s.expires_at > now()
    and a.active = true
    and a.role in ('scanner','admin')
  limit 1;

  if v_username is null then
    return json_build_object('success', false, 'message', 'Scanner authorization required.');
  end if;

  select * into v_student
  from public.students
  where qr_token = p_qr_token
  limit 1;

  insert into public.scanner_logs(
    scanner_username, student_id, usn, full_name, year, result, qr_token
  )
  values(
    v_username,
    v_student.id,
    v_student.usn,
    v_student.full_name,
    v_student.year,
    upper(coalesce(p_result,'INVALID')),
    case when v_student.id is null then null else p_qr_token end
  );

  return json_build_object('success', true);
end;
$$;

revoke all on function public.scanner_log_scan(text,text,text) from public;
grant execute on function public.scanner_log_scan(text,text,text) to anon, authenticated;


create or replace function public.scanner_get_logs(
  p_token text,
  p_limit integer default 40
)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_username text;
  v_result json;
begin
  select a.username into v_username
  from public.staff_sessions s
  join public.staff_accounts a on a.id = s.staff_id
  where s.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    and s.expires_at > now()
    and a.active = true
    and a.role in ('scanner','admin')
  limit 1;

  if v_username is null then
    return '[]'::json;
  end if;

  select coalesce(json_agg(x order by x.scanned_at desc), '[]'::json)
  into v_result
  from (
    select scanned_at, scanner_username, usn, full_name, year, result
    from public.scanner_logs
    order by scanned_at desc
    limit greatest(1, least(coalesce(p_limit,40),100))
  ) x;

  return v_result;
end;
$$;

revoke all on function public.scanner_get_logs(text,integer) from public;
grant execute on function public.scanner_get_logs(text,integer) to anon, authenticated;
